esudo: false
branches:
  only:
  - develop
language: node_js
node_js:
- '7'
before_install:
- 'pwd && ls -als'
install:
- 'pwd && ls -als'
before_script:
- 'pwd && ls -als'
- 'yarn install'
script:
- 'yarn run build:es7-es2016'
- 'yarn test'
after_success:
- 'pwd && ls -als'
- 'ls dist'
after_failure:
- 'pwd && ls -als'
