version: 0.2

#env:
#  variables:
#    AWS_DEFAULT_REGION: "eu-west-1"
#    ACCOUNT_ID: "nnn"
#    IMAGE_NAME: "nnn"
#    CONTAINER_NAME = "nnn"
phases:
  install:
    commands:
    - cp ./settings.xml /root/.m2/settings.xml
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - $(aws ecr get-login --no-include-email --region eu-west-1)
    - echo "Show me the code..."
    - ls -lart
    - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    - IMAGE_TAG=${COMMIT_HASH:=latest}
    - IMAGE=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME
  build:
    commands:
    - echo "Building image ${IMAGE}:${IMAGE_TAG}"
    - docker build --build-arg ACCOUNT_ID=$ACCOUNT_ID -t $IMAGE:latest -t $IMAGE:$IMAGE_TAG .
    - echo "Image build done"
  post_build:
    commands:
    - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"
    - echo Build completed on `date`
    - docker images
    - echo "****"
    - echo Pushing the Docker image...
    - docker push $IMAGE:latest
    - docker push $IMAGE:$IMAGE_TAG
    - printf '[{"name":"%s","imageUri":"%s:%s"}]' $CONTAINER_NAME $IMAGE $IMAGE_TAG > imagedefinitions.json
    - cat imagedefinitions.json
artifacts:
  files: imagedefinitions.json
